version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Llamar a Webhook de n8n
          command: |
            curl -X POST https://n8n.rec.beymedias.com/webhook/cicleci-test \
            -H "Content-Type: application/json" \
            -d '{"message": "¡Despliegue completo!", "build": "<< pipeline.number >>"}'

workflows:
  version: 2
  build-and-notify:
    jobs:
      - build
